### ISSUE TITLE
fortSearch() always returns empty response

### ISSUE THREAD

**Issue by WillCMcC** [cyraxx/pogobuf#10]
Wondering if others are having this issue -- could be any number of things. Every request is giving me a response like this: 

`{ result: 0,
  items_awarded: [],
  gems_awarded: 0,
  pokemon_data_egg: null,
  experience_awarded: 0,
  cooldown_complete_timestamp_ms: Long { low: 0, high: 0, unsigned: false },
  chain_hack_sequence_number: 0 }`

**Comment by renedx** [comment]
Works for me, did you update the player location first using `playerUpdate()`?

**Comment by cyraxx** [comment]
Since it seems to work for others I'm closing this for now.
