### ISSUE TITLE
getMapObjects() return '0' for all kinds of information, including the fort.

### ISSUE THREAD

**Issue by boogiebug** [cyraxx/pogobuf#105]
I used this library to create my own 'scanner' app, and it works great until last few days. The getMapObjects return nothing but all types of game's components with value of "0" (i.e., no all-kinds of Pokemon, no forts not stop, etc.). I do not make any modification on my working code. The information just "disappear". Currently, my best guess is Niantic trick the app by sending me the 'false positive' data?

Just wonder if this have happened to me only or anyone also have the same situation? 

PS: I'm quite sure that my account is not banned. I've tested with the newly created account and it got the same result.

**Comment by SpencerSharkey** [comment]
I'm 99% certain a lot has changed within the API recently. A new version was pushed out, and the old one was finally disabled. 

I don't know what we need to do to get things running again, there is an update to node-pogo-signature that only updates the hash seed for some of the items in the encrypted signature. Apparently, there's also a new encrypt function. 

The bigger issue is the addition of the captcha... that might be a bigger problem to solve.

**Comment by RedSparr0w** [comment]
[The 0.35 API access has been disabled](https://www.reddit.com/r/pokemongodev/comments/56djcm/35_api_has_been_disabled_all_3rd_party_access_is/) | All bots are currently down.

Also captcha not too much of a problem. easy enough to solve using a [method like this](http://i.imgur.com/a6IL2TY.mp4), and keeping bots slow enough to not get too many captchas too quickly

**Comment by cyraxx** [comment]
This is indeed the issue - the API that pogobuf uses is no longer accessible as such.

As far as I can tell not a lot is known about the newer API version and its inner workings yet so there is currently no way to know when, or if at all, pogobuf is going to work with the new API.

**Comment by joelfi** [comment]
Fixed with 5530068aabebf0442cacb3975e1242cda9438d29.
