### ISSUE TITLE
Response is not defined at Client.releasePokemon

### ISSUE THREAD

**Issue by marcowmadeira** [cyraxx/pogobuf#11]
I am trying to release some pokemons, but i keep getting the following error:

> ReferenceError: Response is not defined
>    at Client.releasePokemon (C:\Users\WINDOWS7\Desktop\dx\node_modules\pogobuf\pogobuf\pogobuf.client.js:277:27)
>    at inventory.inventory_delta.inventory_items.forEach.item (C:\Users\WINDOWS7\Desktop\dx\clear_inventory.js:24:14)
>    at Array.forEach (native)
>    at login.login.then.then.then.error (C:\Users\WINDOWS7\Desktop\dx\clear_inventory.js:14:47)
>    at process._tickCallback (internal/process/next_tick.js:103:7)

Here is the code i am using:

```
var pgo = require('pogobuf');

var login = new pgo.GoogleLogin();
var client = new pgo.Client();

login.login('X@gmail.com', 'X').then(token => {
  client.setAuthInfo('google', token);
  client.setPosition(40.766, -73.973);
  return client.init();
}).then(() => {
  return client.getInventory(0);
}).then(inventory => {
  try {
    inventory.inventory_delta.inventory_items.forEach(item => {
      // Check if it isn't a pokemon
      if (!item.inventory_item_data.pokemon_data || item.inventory_item_data.pokemon_data.is_egg)
        return; // skip

      // Required CP
      if (item.inventory_item_data.pokemon_data.cp >= 700)
        return;

      // Transfer pokemon
      client.releasePokemon(item.inventory_item_data.pokemon_data.id.toString()).then(() => {
        console.log('Pokemon gone:', item.inventory_item_data.pokemon_data.pokemon_id, ' CP:', item.inventory_item_data.pokemon_data.cp);
      });
    });
  } catch (error) {
    console.log(error);
  }
});
```

**Comment by cyraxx** [comment]
Thanks @renedx, you fixed it before I could even have a look at what's going on! Thanks again 💯 

I'll push a bugfix release to npm shortly.
