### ISSUE TITLE
Changing nickname of Pokemon is not working

### ISSUE THREAD

**Issue by sysopmatt** [cyraxx/pogobuf#114]
(This is my first issue report on github, so let me know if I'm doing this wrong)

nicknamePokemon() is only able to update Pokemon that were caught before the new update.  Oddly enough, it looks like it's able to rename Pokemon that hatched from eggs yesterday, but the eggs were from before the update.

**Comment by cyraxx** [comment]
Maybe this is related to the latest encryption changes (which we don't support just yet)? Seems a little odd that it would depend on the time the Pokémon have been caught but it's not completely impossible.

**Comment by sysopmatt** [comment]
It's working now, I think it was my bad code.  Sorry about that!
