### ISSUE TITLE
Inventory doesn't provide IncubatorId

### ISSUE THREAD

**Issue by renedx** [cyraxx/pogobuf#12]
The inventory doesn't seem to provide the String ID used to combine Eggs. It seems it should have a response like shown in https://github.com/AeonLucid/POGOProtos/issues/30

E.g. having
```
id: "EggIncubatorProto4435022572568062865"
```

Current response
```
{ modified_timestamp_ms: Long { low: 672078605, high: 342, unsigned: false },
  deleted_item_key: Long { low: 0, high: 0, unsigned: false },
  inventory_item_data: 
   { pokemon_data: null,
     item: { item_id: 901, count: 1, unseen: true },
     pokedex_entry: null,
     player_stats: null,
     player_currency: null,
     player_camera: null,
     inventory_upgrades: null,
     applied_items: null,
     egg_incubators: null,
     pokemon_family: null } }
```

I may be overlooking something :)

**Comment by cyraxx** [comment]
I'm not sure I fully understand the issue. In your response `egg_incubators` is `null` and that's where not just an ID but the whole egg incubator data structure is supposed to be, right?

Do you *have* any incubators? :)

**Comment by renedx** [comment]
Yes that's correct, it should be there. :( But I've no idea why it's not showing up at all.
And this one is the unlimited one I understood (901?, based on the following items list I found: https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/data/items.json).

**Comment by cyraxx** [comment]
I think I found the issue: There are actually two separate inventory items, one of them has `inventory_item_data.item` filled, with item ID 901. The other one has `inventory_item_data.item == null`, however *that* one has `egg_incubators` filled instead.
I guess the first item is just to make it show up in the in-game inventory and the second one is the actual incubator data used for egg hatching.

Give this a try:
```javascript
    .then(() => {
        return client.getInventory();
    })
    .then(inventory => {
        inventory.inventory_delta.inventory_items
            .map(item => item.inventory_item_data)
            .filter(itemData => itemData.egg_incubators !== null)
            .forEach(itemData => {
                console.dir(itemData);
                console.dir(itemData.egg_incubators);
            });
    })
```

**Comment by renedx** [comment]
Oh! I've searched through that list so many times LOL. Thanks! 😄
