### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by frontsideair** [cyraxx/pogobuf#123]
My project depends on pogobuf and the new API doesn't seem to work. I think you probably already know, this is just to track the status.

**Comment by nicoschmitt** [comment]
For now, this is up to date: https://github.com/pogosandbox/pogobuf.
It may be merge into official pogobuf at some poing.

**Comment by Morgul** [comment]
@nicoschmitt I tried your version of pogobuf, but there seems to be an issue with the hash server version, it keeps giving me an error when I try `5100` or `5300`. (I'd make an issue on the fork, but issues seem disabled.)

**Comment by nicoschmitt** [comment]
I've enabled issues. Also current version is 5702 but you are correct 51 or 53 should work (with captcha...)

**Comment by frontsideair** [comment]
We were talking on Discord yesterday, I started using `pogosandbox` fork at `0.57.2` branch on a suggestion and it's working now. Can we cut a release?

**Comment by nicoschmitt** [comment]
First we need a release from @starkevin on node pogo signature

**Comment by cyraxx** [comment]
Release is prepared and ready, just waiting for that node-pogo-signature merge right now.

**Comment by nicoschmitt** [comment]
Everything should now work using npm.

**Comment by frontsideair** [comment]
`1.10.0` works, thanks! (For some reason it works when installed with npm, but not yarn. But I don't really care right now.)

**Comment by Morgul** [comment]
@frontsideair I'm curious how you got it to work for you. I keep getting: `Error: Unsupported version for hashserver: 5100/1.21.0`. I've tried `5100`, and `5720`, but I keep getting the same error. `1.9.0` worked (at least, logged in).

**Comment by nicoschmitt** [comment]
Be sure npm is up to date. Remove node_modules and install npm again.
There are two versions working 4500 (Without hash server) and 5702 (with a hash key)

**Comment by Morgul** [comment]
@nicoschmitt Ah! `5702`. That was what I was missing. I thought it was `5720`. My bad. Can we get these versions documented somewhere on the wiki?

**Comment by starkevin** [comment]
@nicoschmitt where did the NPM version of the signature come from?

**Comment by nicoschmitt** [comment]
I was talking about the version passed to the Api, not the npm version. Or did I miss your question?

**Comment by nicoschmitt** [comment]
And yes fair enough for the wiki.
Documentation is not the part I like 😁
