### ISSUE TITLE
Upgrade ajv to 5.0 beta

### ISSUE THREAD

**Issue by travisfisher** [cyraxx/pogobuf#138]
While using webpack, I'm getting the following warnings:

````
 warning  in ./~/ajv/lib/async.js

96:20-33 Critical dependency: the request of a dependency is an expression

 warning  in ./~/ajv/lib/async.js

119:15-28 Critical dependency: the request of a dependency is an expression

 warning  in ./~/ajv/lib/compile/index.js

13:21-34 Critical dependency: the request of a dependency is an expression
````

Looks like upgrading to one of the 5.0 betas will stop the warnings:

https://github.com/epoberezkin/ajv/issues/373

**Comment by cyraxx** [comment]
ajv is not referenced anywhere by pogobuf so it must be some other dependency that's using it.
If you find out which one then we might be able to update that reference - right now there's nothing I could do.
