### ISSUE TITLE
Getting 403 from pogobuff.GoogleLogin.login()

### ISSUE THREAD

**Issue by Eric-Carlton** [cyraxx/pogobuf#20]
I can't seem to log in to a Google Account. The following code rejects from the GoogleLogin.login() method with a 403: 

`login.login(validUsername, validPassword).then(token => {
		//do stuff with token
	}, err => {
		//err is {} but after some debugging, I've determined it's a 403 from the login() method
	});`

It may be worth mentioning that the account in question has 2FA activated. Could this be causing the problem?

**Comment by MRokas** [comment]
Since you're using 2FA, you have to generate app access password.

**Comment by cyraxx** [comment]
2FA is indeed the issue. I don't think there's much we can do (besides making sure there is an actual error message but that's being handled by #19) so I'm closing for now.

**Comment by MRokas** [comment]
All we can do is give error message like `If you're using 2FA, you've to generate app access password http://google.com/account/path/to/settings/to/set/it`

**Comment by cyraxx** [comment]
We should get that special error message in to avoid confusing people. Do we know which of the two methods is throwing the error - `google.login` or `google.oauth`?

**Comment by Eric-Carlton** [comment]
I'm away from my dev computer for the weekend, but if you don't have an answer by Sunday night I can find out.
