### ISSUE TITLE
releasePokemon tested?

### ISSUE THREAD

**Issue by Jonchun** [cyraxx/pogobuf#22]
I'm using the releasePokemon call and I keep getting 
[ReferenceError: Response is not defined]

I use the exact same code and call evolvePokemon and it works perfectly, so I was wondering if this is implementation error on my end or if something is wrong with the api.

**Comment by cyraxx** [comment]
That should have been fixed in 1.2.0. Can you make sure you are using the latest version on npm?

**Comment by Jonchun** [comment]
Ah, looks like it is fixed in 1.2
