### ISSUE TITLE
Authentication time-outs

### ISSUE THREAD

**Issue by Kyderman** [cyraxx/pogobuf#24]
Hi there,

I've noticed that after a while api calls stop working, as such there is a need for an authentication loop.

Can anyone help me with an example of how I would do that?

Thanks

**Comment by MakuraYami** [comment]
This library just provides an easy way to do the calls and won't implement any logic besides that, so this isn't really the right place to ask that, but sure we can help you out.

```javascript
function login() {
    return auth.login(user, pass).then(token => {
        console.log('Successfully logged in, yay :)');
        return token;
    }).catch(error => {
        console.log('Oh no, an error happened :( we\'ll just retry then.');
    }).then(() => {
        return login();
    });
}
```

I didn't test this code but it is basic logic of dealing with promises.

**Comment by cyraxx** [comment]
I _think_ what @Kyderman meant was that the auth ticket expires after a while of using it so there's a need to re-auth? Which would be similar to what has been discussed in #8.

**Comment by MakuraYami** [comment]
Ha! I guess that is a lot more logical. I thought maybe it was the recent google login outage. Could've worded that better >.>

@Kyderman in that case you'd have to check what error the server is giving when the session times out and call `auth.login()` again and use `client.setAuthInfo(type, token)` again, this _may_ make the current client able to resume, but it might be safer to ditch it and create a new client.

**Comment by renedx** [comment]
@MakuraYami I currently ditch it. It doesn't feel like the correct way, still gotta dig deeper on it to fix it properly. 

Would indeed be nice to make that work. Was working on it, will have a look on it soon tho.

**Comment by Kyderman** [comment]
Ahhh, thats for the help guys.

By any chance, do any of you explicitly know the errors/codes that come back when the timeout occurs?

**Comment by cyraxx** [comment]
@MakuraYami has some experience with this I think.

**Comment by Kyderman** [comment]
That would be great, I think the status_code is 102l but Im having trouble getting the right place to grab it and re-run my code.

Im not sure whether I need to create a new client or just re-login, or whatever else, obviously it takes half hour to test this stuff, so Ima  bit stuck as to what exactly needs to be called, checked and whatever else to get this info.

Any help would be great, if posted here and put in the docs, atleast others wont have issues with it.,

**Comment by Kyderman** [comment]
Through tests I have found that I get up to:

    return client.getMapObjects(cellIDs, Array(cellIDs.length).fill(0))
	.then(mapData => {mapData.... blah blah

When re-auth needs to happen, I cant get inside of this promise/function.

So I need to be able to leverage the status code of 102 at this point to re-auth... but how can I do that? :/

**Comment by SpencerSharkey** [comment]
@renedx have you foundany specific error codes thrown when we need to re-auth, or is it simply a 403?

**Comment by MakuraYami** [comment]
I'm currently doing this in my code

```javascript
this.login().then(token => {
      this.client.setAuthInfo(...);
      this.client.setPosition(...);
      return this.client.init();
}).catch(reason => {
      if (~reason.toString().indexOf('code 102')){
        console.log('status code 102, relogging...');
        return this.relog();
      }
      throw reason;
})
```

I'm a couple commits behind though since I've been busy. We could append status code to the error object so you can simply check `reason.status_code === 102` as a better solution. Right now its counting on the string being made [here](https://github.com/cyraxx/pogobuf/blob/master/pogobuf/pogobuf.client.js#L909)

**Comment by renedx** [comment]
I was working on an auto-login from client, but was getting pretty messy in code. And had to fix these cells being wrong first. :D Will have a look at it tomorrow. Would be nice to have it re-login on its own (passing the loginClient to it, instead of the token).

**Comment by Kyderman** [comment]
@MakuraYami , what is your relogin code like, do you need to make new objects?

**Comment by MakuraYami** [comment]
Simply fetch the new token from auth object, pass it to client. I currently also reset the endpoint but that shouldn't be needed anymore in latest version. I'm sure we'll be able to solve these things Monday.

**Comment by SpencerSharkey** [comment]
The addition of auth_ticket may have made more sense out of this. I think all we have to do is check the timestamp in the auth_ticket object and re-send the auth_info oauth token to request a new auth_ticket for future requests.

**Comment by cyraxx** [comment]
Closing all issues as this repository is no longer being maintained. See README for further information.
