### ISSUE TITLE
NPM release is old

### ISSUE THREAD

**Issue by BuffCoder** [cyraxx/pogobuf#25]
Just a heads up, it looks like your npm release is an older version and doesn't contain the `utils` part needed for the inventory example.

Awesome work with this -- it's making tinkering around with the Pogo API real fun.  I'll PR some additional examples as I learn more.

**Comment by cyraxx** [comment]
The current release (1.3.0) has been pushed to npm just about two hours ago, did you try `npm update`?

And thanks for the kind works. looking forward to your PR!

**Comment by BuffCoder** [comment]
That was the problem, thank you!  I had pulled it down in the morning and didn't have a chance to try to decode my inventory until the afternoon.

Thanks again!

Brandon Krueger
