### ISSUE TITLE
typescript typings

### ISSUE THREAD

**Issue by MRokas** [cyraxx/pogobuf#3]
Can we expect .d.ts for this project? I would gladly help with that,

**Comment by cyraxx** [comment]
I don't have any TypeScript experience so I'm not really sure how to go about creating the type definition. If you could assist or point me in the right direction I'll gladly do what I can.

**Comment by MRokas** [comment]
I'm almost done, just gotta

**Comment by cyraxx** [comment]
Yeah, I haven't gotten around to adding JSDoc comments with variable types for all the API methods yet.

For now you can look up the corresponding message definitions in the [.proto file](https://github.com/cyraxx/node-pogo-protos/blob/master/proto/POGOProtos.Networking.Requests.Messages.proto) and get the types from there.

**Comment by MRokas** [comment]
Oh cool, thanks. I will get it done tomorrow.

**Comment by Twentyfoureyes** [comment]
@MRokas did you ever finish writing the d.ts file?

**Comment by Alph44rchitect** [comment]
@MRokas are you still working on the typings?
