### ISSUE TITLE
No wild, cathable or nearby pokemon found

### ISSUE THREAD

**Issue by PabloArjonilla** [cyraxx/pogobuf#30]
For some reason, I can't get ant of those pokemons using the api. But I can see several on my phone under the same account.

Is anyone else having this same problem?

**Comment by cyraxx** [comment]
Niantic seems to have rolled out some API changes targeting third party clients. The details aren't fully known yet.

I just tested and I still get Pokémon in *one* of the map cells I'm querying but none of the others. Maybe they introduced a certain radius within which you get Pokémon responses.

**Comment by renedx** [comment]
Mmm I got plenty responses on multiple cells. But I do update cells each 30 seconds with max of 21 cells. Not yet sure how the app updates, still need to inspect that.

**Comment by BuffCoder** [comment]
Not sure if you're still experiencing this problem.  I was able to search a cell and find a catchable pokemon and nearby pokemon.

I would...
1.  Check your coordinates and make sure you're using valid lat/longs.  Plug em into google maps to verify your character is where you think it should be
2. Load up [Pokevision](https://pokevision.com/) and see if it finds any

**Comment by cyraxx** [comment]
If it works for others I guess we can close this then?

**Comment by PabloArjonilla** [comment]
Thanks everyone!
