### ISSUE TITLE
Request throttling

### ISSUE THREAD

**Issue by cyraxx** [cyraxx/pogobuf#31]
I just Implemented a very simple throttling of API calls to 1 per second: https://github.com/cyraxx/pogobuf/commit/15ca4ff45d5d3c9132b5d1d3bc703aeb3d14f696

This gets rid of the code 52 errors for now but I think you can actually do a little more than 1 per second.

One idea would be to don't do any preemptive throttling and instead retry requests (for a maximum of, say, 5 times) with a little delay whenever a status 52 response is received. That would be a little more robust as it would also handle the occasional 52 you get when the servers are overloaded.

**Comment by renedx** [comment]
I'm currently delaying them (with bluebird delay) with 300ms by default. 
 - Encounter Pokemon has delay of 2000ms
 - Catching Pokemon has a delay between 300ms and 1200ms.
   - If result 4 while hit (out of ball) delay of 600ms (animation)
 - Moving item from inventory has delay of 900ms
 - Using item for capture has delay of 2000ms
 - Using incubator has delay of 3000ms

This works exceptionally well (put here for reference / others).

These are made-up numbers based on how slow the UI feels for me. It may be a nice idea to use throttling besides real-human throttling. As you cannot activate 3 incubators at once within 1 second for example. Same for throwing balls at a Pokemon after it came out of the ball. 

Just queue'n them and delaying; 300ms would be enough AFAIK.

**Comment by Morgul** [comment]
I'd recommend implementing retry with [bluebird-retry](https://github.com/demmer/bluebird-retry), and exposing those as options you can pass to the client object. It has a very nice backoff strategy and I've used it in some production AWS code to great success.

Regarding the throttling; I'd love to see this changed to be a client option. Adding an `options` object to the client constructor might additionally be a little future proof for other options that might want to be added.

**Comment by Tuxity** [comment]
I saw on reddit people saying over 3req/s you will get the error 52.

**Comment by cyraxx** [comment]
I've increased the throttled rate to 2/second and that seems to still work fine. Forgot to mention, it can be turned off with `client.enableThrottling(false)`.

I will look into bluebird-retry, thanks for the pointer!

"Human-like" throttling based on how long it would take a user to trigger the individual actions however is not something that I'll include in the client - the client's goal is simply to provide a way of calling API functions without getting errors. Whether you use those to perfectly mimic human behavior or do something that is obvious botting is up to you.

I *could* see logic for "realistic" delays as a separate class or maybe a client subclass if someone wants to contribute that, but that would be outside the scope of this issue.

**Comment by Morgul** [comment]
What I'm currently doing is disabling throttling, and then doing my own throttling to 3/sec. Being able to control the throttling via a parameter (even if you just exposed a `setThrottleRate(timeMS)` function) would be more convenient.

**Comment by cyraxx** [comment]
I agree that it should be configurable. I just put something in right now to avoid getting error 52 all the time, it's not final at all. I'll spend some more time on this later.

**Comment by cyraxx** [comment]
Throttle delay can now be configured (`setThrottleDelay(0)` to turn it off).

This is still temporary though and might change.

**Comment by ChrisKader** [comment]
While the current solution throttles if RPC calls are made one at a time, it does not throttle batch calls being made in one RPC call. At this point, I am unable to get consistent data with the batch functions but I get the info needed when I do one call at a time. It may be good to re-think the batch function and have them just do individual RPC calls. I would be more than happy to take this on.

**Comment by cyraxx** [comment]
Are you saying the limit of ~3/s applies to the actual (sub-)requests? I had always just assumed it applied to the number of RPC envelopes. If it's the request messages then that does make things complicated for batch mode.

If possible I'd like to keep the batch mode as a single RPC request, that's basically the whole point of it now.

**Comment by cyraxx** [comment]
I've just implemented something using bluebird-retry. The approach is really simple: Whenever a request fails (that *includes* code 52), retry it up to 4 more times, with increasing delay.

I've run some test, including batch calls that have a whole bunch of requests, and it seems to work fine. There's the occasional error 52 as expected, but it just tries again and it works. Sometimes there's no 52 at all, in that case there's no time wasted with unnecessary delays.

The beauty of this is that it handles both the "rate limit" 52s as well as the "server busy" 52s, and even the HTTP 502 we sometimes get when the servers are overloaded.

I think this is the way to go. And of course you'll still be able to turn it off if you want to handle it yourself.

**Comment by renedx** [comment]
Sounds good, looking forward to it. The 502 randomness is pretty annoying currently. Love the exponential backoff approach on the retry's. That's a nice take on it.

**Comment by cyraxx** [comment]
Pushed it now. Let me know how it works for you!

**Comment by renedx** [comment]
Been inspecting the real client for a while now and it seems to ditch the whole batch if one of it failed and resend the whole batch again. It continues doing so until it has full response. This especially can be found in the start-up fase, where as sometimes not all requests receive a response. 

Currently hitting the 5 times max easy, while the original app just keeps trying. But always in a batch. Mmm.

**Comment by cyraxx** [comment]
Weird that you're hitting the max easily, I've never seen more than one, maybe two retries. With the retry settings (300 ms base delay, backoff factor of 2) the delay between try 4 and 5 will be almost 5 seconds, I'd have thought that should be more than enough to reset the rate limit.

By retrying the whole batch do you mean multiple RPC envelopes or just one envelope containing multiple requests (i.e. what pogobuf's batch mode does)? Because if you're using batch mode and that RPC request fails we also retry the whole thing.

**Comment by renedx** [comment]
It was ERR 502 when I hit it easy. AFAIK that happens when the server is too busy. So it is not a big problem (if I'm correct), it doesn't hit easy on the 52 anymore. 

I had it run overnight to make sure it was OK and besides some max 5's on 502 (I re-log in such case), it eventually crashed on;
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I didn't search yet exactly what TLSSocket that is (could also be Google's for re-auth). Anyone else ran into this?

**Comment by Morgul** [comment]
`TLSSocket` is the internal node class for doing HTTPS, that's all. 

I've run into this occasionally. Your right that it's related to server load, I think. My little script would crash and restarting it would work fine... Haven't tried anything long running yet. But my script never runs fur more that a few seconds, so it can't be auth related in my case.

**Comment by renedx** [comment]
Understood, but within pogobuf `request` is being used. Something initializes a TLS connection without listening on the `error` event. Thats the reason it crashes fully instead of nicely throwing the error. I assume it cannot be `request` lib, but I may be wrong there of course.

**Comment by Morgul** [comment]
Request uses node's http classes internally, so that doesn't surprise me. 

As for the error handling, it's probably a small bug with pogobuf. Maybe open a new issue?

**Comment by cyraxx** [comment]
`request` is supposed to send all errors to our callback, so if it is caused by a `request` request (heh) then it would actually be a bug in `request`. Maybe it is somewhere in the Google auth instead?

Anyway, pretty sure that would be a separate issue. The request throttling seems to be dealt with, right? So we can close here and push the new version to npm?

**Comment by renedx** [comment]
Yup, request throttling is OK. 👍  Changed everything into batch anyway, so I'm personally not even hitting limits without it anymore anyway :)
