### ISSUE TITLE
Getting stardust and candy costs for powering up and evolving

### ISSUE THREAD

**Issue by Jovaage** [cyraxx/pogobuf#32]
I can't seem to find this data anywhere.
Is it not sent? Is it perhaps calculated on client?
Or am I just not able to find it?

**Comment by cyraxx** [comment]
Try `downloadItemTemplates()` and then look through the results - there is a `pokemon_upgrades` field in there that has the candy and stardust cost for each Pokémon level.

There's also `pokemon_settings` which should have the evolution data.
