### ISSUE TITLE
Slack or Discord

### ISSUE THREAD

**Issue by devdaniel** [cyraxx/pogobuf#35]
I suggest we should create/join a Slack or Discord server for dev/support.

**Comment by cyraxx** [comment]
There's the [/r/pokemongodev Discord](https://www.reddit.com/r/pokemongodev/comments/4v6n8n/official_discord_server_for_rpokemongodev/) that has a `#node-dev` channel. TBH I'm not a big fan of Discord though.

I'm also hanging out in [the pgoapi Slack](https://github.com/tejado/pgoapi#contribution) which is obviously focused on Python but still a good resource. Maybe they'd let us have a channel there? I think that would be the most convenient option.

**Comment by Morgul** [comment]
I'm not a big fan of Discord either; I like Slack much better, but even then it's got some issues for open communities. Easiest might be [Gitter](https://gitter.im/), tbh.

Though if you're just looking for something slack-like, I run a [Rocket.Chat](https://rocket.chat/) chat instance I'd be more than willing to let you have channels on. (I've already got a #pokemongo-hacking channel for some of my coworkers who've been reverse engineering things.) Just let me know if that sounds like it'd work for you.

**Comment by Snorflake** [comment]
I'm the other way, I'd love to have a discord.

**Comment by cyraxx** [comment]
We've pretty much taken over `#node-dev` in the /r/pokemongodev Discord (linked above) now 😃 

I'm still not a huge fan of Discord and would prefer Slack but there's already a user base there and also has general API discussion.

**Comment by Infient** [comment]
I support the idea of our own Slack/Discord since the /r/pokemongodev Discord has grown and is now pretty much full of people.

**Comment by cyraxx** [comment]
We have a Slack now! :tada: (Thanks @joelfi)
https://pogobufslack.herokuapp.com/
