### ISSUE TITLE
Getting candies, and getting how many candies a pokemon needs to upgrade/evolve.

### ISSUE THREAD

**Issue by Snorflake** [cyraxx/pogobuf#36]
I coulnd't see anything in the API about this, does anyone know how to do what's requested in the title?

**Comment by cyraxx** [comment]
The candy requirements are somewhere in the `pokemon_settings` in the `downloadItemTemplates()` response. They vary by Pokémon level.

The candy awarded after catching a Pokémon is in the `capture_award.candy` of the `catchPokemon()` response. And also the amount of candy you have is in the inventory.

**Comment by Snorflake** [comment]
I checked the inventory and nothing was inside of splitInventory().candies

**Comment by cyraxx** [comment]
There was a bug that has been fixed in https://github.com/cyraxx/pogobuf/commit/d99d148bd8a255e0e98f78f4b5949816df760f59.

The fix hasn't been pushed to npm yet so if you're on the latest npm version you'll need to switch to latest dev or just patch in the fix manually.
