### ISSUE TITLE
How to stop the session?

### ISSUE THREAD

**Issue by ikonduktor** [cyraxx/pogobuf#38]
For example, I want have 2 sessions in one node api, one after one. But when i use the second Google login/pass, there is an old user "ingame" yet. How can I stop old User playind and start new User playing session?

**Comment by MakuraYami** [comment]
Initialise two clients. 

```
let user1 = new pogobuf.Client();
let user2 = new pogobuf.Client();
```

Then use the auth objects to fetch tokens and give them to each client individually.

**Comment by cyraxx** [comment]
You could technically also call `client.setAuthInfo()` and `client.init()` again (that will properly reset stuff since a few commits ago).

But simply creating a new client instance is easier.

**Comment by ikonduktor** [comment]
No, I need just to kill current user session. How can I do that? I have already use "delete client;", but in didn't help

**Comment by ikonduktor** [comment]
I fix my problem, thank you.
