### ISSUE TITLE
How to detect Pokemon nearby?

### ISSUE THREAD

**Issue by DaAwesomeRazor** [cyraxx/pogobuf#45]
Just wondering if there is some event or something tha tells you when you encounter a Pokemon

**Comment by tonghae** [comment]
+1, need to know this too. I want to make a service posting selected pokemons in specific area with their despawn timers to Twitter.

**Comment by renedx** [comment]
The `getMapObjects` will respond with the cells filled. This has a `catchable_pokemons` array that has the spawn point, despawn time and pokemon_id in it.

**Comment by tonghae** [comment]
Yeah, I see, thanks for the tip! But what's the difference between catchable_pokemons, wild_pokemons and nearby_pokemons?

**Comment by renedx** [comment]
I've not seen any diff between catchable and wild, but if it is in wild but not in catchable it isn't catchable. Nearby is for the game UI to show what Pokemon are nearby including the meters. But that's just not working.

**Comment by DaAwesomeRazor** [comment]
Thanks man! Helped a lot

**Comment by tonghae** [comment]
But how to use second argument, "sinceTimestamps"?

**Comment by DaAwesomeRazor** [comment]
`    .then(() => {
        return client.getMapObjects();
    })
	
	.then(mapObjects => {
		console.log(mapObjects)
	})`

**Comment by tonghae** [comment]
.then(mapObjects => { ... })

**Comment by DaAwesomeRazor** [comment]
@tonghae Thanks :D, I  think I can get it working now

**Comment by renedx** [comment]
@tonghae second argument is an array of zero's. It's the last scanned timed, but the original app doesn't do anything with that yet.

**Comment by renedx** [comment]
I've proposed an example script for this;
#48

**Comment by tonghae** [comment]
It may be a kinda stupid question but... is it possible to query game server only about catchable pokemons in the area, without any other info (e.g. gyms, pokestops etc)? I see that to scan large enough zone (like Manhattan) for rare pokemons (Raichu, Venosaur, Dragonite etc) I need 10+ accounts working simultaneously and it can generate a lot of totally useless info increasing my server's traffic.

**Comment by renedx** [comment]
Nop it doesn't. Because it is not the purpose to only get Pokémon hahah.
