### ISSUE TITLE
Possibly switch over to pokemon-go-protobufjs-node

### ISSUE THREAD

**Issue by cyraxx** [cyraxx/pogobuf#5]
Depending on what @rastapasta comes up with it might be worthwhile to ditch [node-pogo-protos](https://github.com/cyraxx/node-pogo-protos) and go with [pokemon-go-protobufjs-node](https://github.com/rastapasta/pokemon-go-protobufjs-node) instead.

See also the discussion at https://github.com/AeonLucid/POGOProtos/pull/58

**Comment by renedx** [comment]
Do you know if there any examples on using pokemon-go-protobufjs-node? Otherwise I'll figure it out anyway; just would help in time.

As I'm running into more of these proto3 issues (https://github.com/cyraxx/pogobuf/issues/2#issuecomment-235232806) I'm willing to help on this. Free to take?

**Comment by cyraxx** [comment]
I was going to wait a few days to see what direction @rastapasta's implementation takes in case there might be breaking changes. From the short discussion we've had it sounded like he isn't finished with it yet.

The switchover itself shouldn't be more than including the other package instead of node-pogo-protos.

**Comment by renedx** [comment]
I see, didn't properly read that part. Awesome.

**Comment by renedx** [comment]
Now running into following;
```
Error: Illegal wire type for field Message.Field .POGOProtos.Networking.Responses.LevelUpRewardsResponse.items_unlocked: 2 (0 expected)
```

Not sure worth mentioning? :)

**Comment by cyraxx** [comment]
Yeah, probably another case of a missing `packed` attribute :/

Basically I'd like to make the switch but I'm not sure what @rastapasta's plans are for pokemon-go-protobufjs-node, i.e. how mature it is, whether there might be breaking changes coming and what else he has planned. Hopefully we'll see some activity from him soon-ish :)

**Comment by renedx** [comment]
I'm not so familiar with proto unfortunately, tried `[packed=true]`but didn't work (crashes on illegal `[`). Wouldn't https://github.com/rastapasta/pokemon-go-protobuf-node be his new work?

**Comment by cyraxx** [comment]
The attribute needs to be added to the `.proto` file like so:
`repeated .POGOProtos.Inventory.Item.ItemId items_unlocked = 4 [packed=true];`

pokemon-go-protobuf-node is a separate package that uses the native protobuf library which doesn't work on all platforms (and has a different API).
pokemon-go-protobufjs-node and node-pogo-protos are using protobuf.js instead which is a pure JS implementation of protobuf.

**Comment by MakuraYami** [comment]
I'm in favour of switching, the [pokemon-go-protobuf-node](https://github.com/rastapasta/pokemon-go-protobuf-node) seems more up to date and the "Illegal wire type" errors that @renedx mentioned pretty much made this lib unusable in it's current state.

**Comment by cyraxx** [comment]
Yeah you're right, something needs to happen. I'll look into it in a little bit.

**Comment by cyraxx** [comment]
I've added a workaround to node-pogo-protos so if you just `npm update` all the illegal wire type errors should be gone.

**Comment by renedx** [comment]
Been using the updated version now, seems OK. I've ran into six `POGOProtos.Data.Capture.CaptureAward.activity_type`'s but nothing else so far. Not sure why that one isn't working properly?

**Comment by renedx** [comment]
Mmm also CheckAwardedBadgesResponse, so must be on my side. I'm looking into it. Prop something with node_modules dir.

**Comment by cyraxx** [comment]
Nothing has happened in the pokemon-go-protobufjs-node repository for a while and my own fix for the protobuf.js proto3 bug seems to be working will so I don't see the need to switch anymore.
