### ISSUE TITLE
getCellIDs not a function

### ISSUE THREAD

**Issue by bloigge** [cyraxx/pogobuf#52]
Hi - I am getting this error since last update. Looks like the getCellIDs function got lost

```
var cellIDs = pogobuf.Utils.getCellIDs(lat, lng);
                                    ^
TypeError: pogobuf.Utils.getCellIDs is not a function

```

**Comment by cyraxx** [comment]
It's the other way around actually, the function only got introduced recently but the example code has already been updated to reflect it. If you're using the latest npm version (1.4.0) you can use the examples from that version: https://github.com/cyraxx/pogobuf/tree/v1.4.0/examples

**Comment by bloigge** [comment]
Ah I see - guess I was my time ahead. Thanks for the great repository!
