### ISSUE TITLE
[Error: Request count does not match response count]

### ISSUE THREAD

**Issue by jimdubbs** [cyraxx/pogobuf#53]
[Error: Request count does not match response count
What exactly does this error mean? I periodically select a client and do a heartbeat + getGymDetails. Occasionally I see the getGymDetails promise rejected with this error but dont quite know how to solve it...any insight?

**Comment by cyraxx** [comment]
It means that we sent the server some requests but didn't get a response back for at least one of them (even though the status code suggests that the requests were successful).

What does your request look like? Do you use batch mode?

**Comment by jimdubbs** [comment]
After updating to the latest version I no longer seem to get this error...however after 2 itterations of a loop now I'm getting this:

Unhandled rejection Error: operation timed out after 5059 ms, 5 tries with error: Status code 102 received from RPC

Basically I have an interval loop that runs ever 15 mins. within that I loop through a handful of gyms (I've setup a client for each gym to prevent jumping around the map with 1 client). all seems great the first couple of itterations but then I get that error. Anywhere I can lookup what status code 102 is?

Heres a short snippet of my code..

```
var cellIDs = getCellIDs(10, lat, long);
                       
client.setPosition(lat, long);
client.getMapObjects(cellIDs, Array(cellIDs.length).fill(0))
.then(mapObjects => {
        client.getGymDetails(gym.gym_state.fort_data.id, lat, long)
           .then(function (data) {
            //do stuff
          });
 });                                       
```

**Comment by cyraxx** [comment]
102 means your auth token expired. See #24 and also #8 for further discussion. We're planning to have a system in place that automatically re-auths in this case but that does not exist yet.

BTW, with the latest dev version it also won't retry when it hits error 102 so you don't have that five second delay.

**Comment by jimdubbs** [comment]
ahh ok thanks!
