### ISSUE TITLE
getMapObjects empty

### ISSUE THREAD

**Issue by mifi** [cyraxx/pogobuf#57]
A couple of hours ago Niantic started blocking the old version of the iOS/Android app.
Just as I was coding/testing my new script using pogobuf, suddenly getMapObjects started returning only empty results. It seems that now they have changed the protocol or started detecting still running old "apps" or unofficial API clients.

So it's back to the drawing board. Already blew up on reddit:
https://www.reddit.com/r/pokemongodev/comments/4w0jum/all_ptcgoogle_logins_failing_from_api/
https://www.reddit.com/r/pokemongodev/comments/4w0mtr/getting_0_pokemon_upserted_in_last_few_minutes/

**Comment by cyraxx** [comment]
There's a lot of misinformation out there. I've dug through some of the raw requests/responses that someone captured and posted my findings in a comment on here:
https://www.reddit.com/r/pokemongodev/comments/4w124h/pokemon_go_antibots_reverse_engineering/

That's all I can do for now. And now, we wait ¯\\\_(ツ)_/¯

**Comment by tonghae** [comment]
Ok, looks like a global API update. Will be waiting for fixes.

**Comment by hoodoos** [comment]
@cyraxx hey there, any news on it? map thread is a mess :)

**Comment by cyraxx** [comment]
A bunch of very skilled people are working on it and have made some progress however it's still a long way to go until we'll be able to reproduce the necessary changes in the API requests, so no ETA as of yet.

**Comment by Tuxity** [comment]
It's good 😊😊😊
https://github.com/keyphact/pgoapi

Thx to those crazy guys, they did it !

**Comment by jimdubbs** [comment]
From what I gather the issue has been solved and the python library has been updated. Any sort of ETA
on when we can expect this repo to be updated?

**Comment by SuigetsuSake** [comment]
I don't know what their fix is modifying exactly but shouldn't 'node-pogo-protos' also be updated for this to work ?

**Comment by cyraxx** [comment]
Well @Tuxity since I was one of the "crazy guys", thanks for the kind words :wink:

Right now there is a native library _floating around the internet_ that has the encryption code for the Signature (aka Unknown6). I'll have to figure out if and how we want to integrate the native code into pogobuf. But first I need some sleep - so be patient please.

**Comment by Tuxity** [comment]
Thanks cyraxx ! I'm gonna check the implementation too with friends this weekend

**Comment by jimdubbs** [comment]
@cyraxx what is it a dll? we could use edgeJS to call a dll quite easily.

**Comment by mifi** [comment]
Looks like someone wrote a node wrapper around the "encrypt" C lib:
https://github.com/SpencerSharkey/node-pogo-signature
However for me it's not compiling (mac)
Best would be to port it to node.js i guess.

**Comment by Tuxity** [comment]
They have implemented that lib here btw https://github.com/Armax/Pokemon-GO-node-api/commit/8427f0c5932fabec57d24a6565f258ba0de865e1

**Comment by cyraxx** [comment]
Working on it right now :)

**Comment by Tuxity** [comment]
Ah okay ! I was too 😄  Gonna let you finish so

**Comment by SpencerSharkey** [comment]
https://github.com/cyraxx/pogobuf/pull/62

any help?

**Comment by Tuxity** [comment]
You're quick @SpencerSharkey 😄

**Comment by cyraxx** [comment]
Boom. Done. 😃

**Comment by rastapasta** [comment]
big love!
