### ISSUE TITLE
Add JSDoc comments for all the API call methods

### ISSUE THREAD

**Issue by cyraxx** [cyraxx/pogobuf#6]
The purpose/description of each method can pretty much be inferred from its name. The parameter types can be looked up in the [Messages.proto](https://github.com/cyraxx/node-pogo-protos/blob/master/proto/POGOProtos.Networking.Requests.Messages.proto) file.

**Comment by cyraxx** [comment]
Also the README is getting pretty long. Might be time to move the API documentation over to a Wiki.

**Comment by cyraxx** [comment]
The API documentation is now in the wiki (thanks @Infient) and there has been some progress on documenting the API methods. If anyone would like to help, head over to [the API wiki page](https://github.com/cyraxx/pogobuf/wiki/pogobuf.Client-Pokémon-Go-API-Methods) and add some method documentation.

**Comment by cyraxx** [comment]
I think @MakuraYami pretty much has this handled in the 2.0 branch - is that correct? Can we close this?

**Comment by MakuraYami** [comment]
There are still some missing but yeah, it's not much. We can finish that up before its done, ill close this.
