### ISSUE TITLE
Usage of bluebird-retry with webpack

### ISSUE THREAD

**Issue by mbeaudru** [cyraxx/pogobuf#66]
Hi,

I'm having an issue building with webpack using pogobuf because it relies on bluebird-retry which seems to make the app crash.

Here is the warning I got on my OS console:

```
WARNING in ./~/bluebird-retry/browser/bluebird-retry.js
Critical dependencies:
1:486-493 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/bluebird-retry/browser/bluebird-retry.js 1:486-493
```

And the issue logged in my browser:

```
bluebird-retry.js:108Uncaught Error: Parse error at line 1: unexpected '<'
```

Any guess ?

**Comment by MakuraYami** [comment]
It would not work in the browser anyway. Are you building webpack for electron?

**Comment by cyraxx** [comment]
I think this would be an issue for [bluebird-retry](https://github.com/demmer/bluebird-retry), no?

**Comment by MRokas** [comment]
Webpack is used to bundle files for browser, there's no need todo that for node.js

**Comment by cyraxx** [comment]
In any case I'm pretty sure this is bluebird-retry related and not pogobuf so I'll close this.

**Comment by vinnymac** [comment]
For anyone who comes across this issue. If you want to build pogobuf for electron using webpack, in your configuration you can add this to have it stop compiling these dependencies. You must deliver these dependencies to your user when packaging your binary instead.

```javascript
  externals: [
    'pogobuf',
    'node-pogo-protos'
  ],
```

If you wanted to explicitly tell it to stop parsing bluebird-retry, you would do this instead, but I don't think that is what you want.

```javascript
  module: {
    noParse: [
      /node_modules\/bluebird-retry\/browser\/bluebird-retry.js/
    ],

    loaders: [...]
  },
```

**Comment by simonh1000** [comment]
Why is the library only usable with node, and thus not to power a webapp directly?

**Comment by cyraxx** [comment]
If by webapp you're referring to a regular browser opening a website, that's not going to work due to same-origin policy. The app wouldn't be able to make any requests to Niantic's servers.

But if that's not an issue in your environment then I don't see why it shouldn't work in a web app as long as you have a suitable module loader since the library and all of its dependencies are completely pure JS.
