### ISSUE TITLE
sfidaActionLog - Illegal wire type

### ISSUE THREAD

**Issue by maierfelix** [cyraxx/pogobuf#67]
When calling sfidaActionLog:
````
Unhandled rejection Error: Illegal wire type for field Message.Field .POGOProtos.Data.Logs.CatchPokemonLogEntry.pokemon_data_id: 1 (0 expected)
````

Problem with POGOProtos itself?

**Comment by SpencerSharkey** [comment]
Possibly affected by the app updates today?

**Comment by maierfelix** [comment]
Im using 0.31.0 in a spoofed network.

**Comment by cyraxx** [comment]
That would be an issue with POGOProtos, yes. I don't see an open issue or any recent commits related to this on their repo yet though.

**Comment by maierfelix** [comment]
Similar problem, left unfixed: [https://github.com/tejado/pgoapi/issues/207](https://github.com/tejado/pgoapi/issues/207)

I will open an issue.
