### ISSUE TITLE
gym_points .high always zero

### ISSUE THREAD

**Issue by akarupt** [cyraxx/pogobuf#70]

**Comment by SpencerSharkey** [comment]
i think gym_points is an int64, meaning you have to convert it from the native (long)[https://www.npmjs.com/package/long] type...

you should simply be able to do `.toNumber()` to get the JS number.

**Comment by joelfi** [comment]
And if `.toNumber()` does not work, you could do `parseInt(variablehere.toString(), 10)` (convert to string and then to integer). Warning! The integer could be too big for JavaScript to handle, so be careful.

**Comment by akarupt** [comment]
.high is allways zero but with same code .low have value... 
"owned_by_team": 1,
			"guard_pokemon_id": 134,
			"guard_pokemon_cp": 0,
			"gym_points": {
				"low": 6315,
				"high": 0,
				"unsigned": false
			},

**Comment by joelfi** [comment]
To get convert `gym_points` to integer, you should do this:

```javascript
var gym_points = parseInt(OBJECT_STRUCTURE_HERE.gym_points.toString(), 10);
```
Or replace `var gym_points` with `OBJECT_STRUCTURE_HERE.gym_points` to replace the thing in the object.

**Comment by akarupt** [comment]
ahhhh ok. Thanku :)
