### ISSUE TITLE
getMapObjects returns an empty mapObject (catchable pokemon example).

### ISSUE THREAD

**Issue by LiquidSnake2ITA** [cyraxx/pogobuf#72]
The code is the same in the "list-catchable-pokemon.js" file. The response is always empty. Does anyone has the same issue?

**Comment by cyraxx** [comment]
Are you running the latest version (1.5.0)?

**Comment by LiquidSnake2ITA** [comment]
Yes, here's my package.json:

`"bluebird":` "^3.4.1",
 "node-pogo-protos": "^1.2.0",
 "pogobuf": "1.5.0",`

**Comment by tonghae** [comment]
Looks like IP ban now allows accounts to be authorized but returns empty results. Yesterday I received 403 on sign in attempts so I bought a private proxy to use with. Now I'm able to sign in from previously banned IP (DigitalOcean) but receiving empty getMapObjects results. Proxy IP seems to be banned to because I see similar empty results while using it.

So your IP may be banned too. Not sure, but for my case it is.

**Comment by LiquidSnake2ITA** [comment]
I don't see here the comment left by Sergey, however I've done some tests using different IPs but I've got always the same response:

```
...,
    "s2_cell_id": {
      "low": -1073741824,
      "high": 370547420,
      "unsigned": true

    },
    "current_timestamp_ms": {
      "low": 1945308169,
      "high": 342,
      "unsigned": false

    },
    "forts": [
      
    ],
    "spawn_points": [
      
    ],
    "deleted_objects": [
      
    ],
    "is_truncated_list": false,
    "fort_summaries": [
      
    ],
    "decimated_spawn_points": [
      
    ],
    "wild_pokemons": [
      
    ],
    "catchable_pokemons": [
      
    ],
    "nearby_pokemons": [
      
    ], ...
```

The strange thing is that if I try to log in with the latest PGO app, using this account, from the same IP, it works as expected.

**Comment by joelfi** [comment]
Have you tried to `console.log` the cells you and putting the cell array in http://s2map.com/ to check if the cells are in the correct positions?

**Comment by LiquidSnake2ITA** [comment]
@joelfi you've got the point! Seems that for some reason I was trying to retrieve data using wrong coordinates. Thanks for the useful link, we can close :)
