### ISSUE TITLE
Fetching RPC endpoint failed

### ISSUE THREAD

**Issue by Jndachenhaus** [cyraxx/pogobuf#73]
Receiving this error although I am directly following one of the examples (inventory.js)
```{ [Error: operation timed out after 4673 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 100]
  failure: [Error: Fetching RPC endpoint failed, received status code 100],
  code: 'ETIMEDOUT' }```
Status code 100 wasn't listed in the wiki either

**Comment by Jndachenhaus** [comment]
Figured it out, really dumb mistake.

**Comment by pablonazareno** [comment]
Same issue.

What was the mistake?

**Comment by cyraxx** [comment]
I haven't seen status code 100 before, would like to know what it is too.

**Comment by Jndachenhaus** [comment]
I don't quite remember at this point, but I think it was either the fact that I inputted the lat/lng as a string, or that I capitalized "PTC" or "Google" as the provider in setAuthIssue(provider, token)

I'll try to replicate it later to see exactly what it was

**Comment by Jndachenhaus** [comment]
After changing `client.setAuthInfo("PTC", token)` the error was reproduced. I believe that it is only due to the capitalization of the provider.

Error: `after 4615 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 100(…)`

**Comment by cyraxx** [comment]
So status code 100 seems to be invalid auth provider name - we'll put that in the wiki, thanks!
