### ISSUE TITLE
What token to pass into Google loginWithToken

### ISSUE THREAD

**Issue by thisbejim** [cyraxx/pogobuf#74]
What token are you supposed to pass into Google's [loginWithToken](https://github.com/cyraxx/pogobuf/wiki/pogobuf.GoogleLogin-Methods#loginwithtokenusername-token--promise)? An oauth access token?

Thanks for your help.

**Comment by cyraxx** [comment]
A Google master token, which you usually get from `GoogleLogin.getMasterTaken(username, password)`.

**Comment by thisbejim** [comment]
Is there any way to get the master token without requiring a users password? e.g. Using the google oauth flow or something like that? Just because people don't like handing out their passwords. Thanks again for your time.

**Comment by thisbejim** [comment]
So you can better understand what I am trying to do: I'm attempting to use Firebase's [Google Login](https://firebase.google.com/docs/auth/web/google-signin), which returns an access token along with some other details, so that users don't have to enter their passwords. Are there special scopes I have to ask for to achieve this?

**Comment by thisbejim** [comment]
I did a ton of reading on oauth tokens and realised this is just not possible.

**Comment by edswartz** [comment]
I was going down this road as well. Would there be no way to pass an Oath token (https://developers.google.com/identity/sign-in/web/backend-auth) through Pogobuf?  Again, trying to avoid users having to enter passwords.  It would be great to pass the token_id instead of password.
