### ISSUE TITLE
Missed node-geocoder

### ISSUE THREAD

**Issue by glmn** [cyraxx/pogobuf#75]
Missed node-geocoder dependency for gym-details.js example

**Comment by rnd256** [comment]
Can you provide more detail on the issue? It looks like node-geocoder is imported in gym-details.js as expected.

**Comment by joelfi** [comment]
I think this issue is about excluding the `node-gecoder` depency in package.json. Can @glmn confirm?

**Comment by cyraxx** [comment]
It says [at the top of the file](https://github.com/cyraxx/pogobuf/blob/master/examples/gym-details.js#L14) that you need the additional package.

So just install it manually using `npm install node-geocoder` - or remove the geocoding completely and use hardcoded lat/lng coordinates like in the other examples.
