### ISSUE TITLE
getEnumKeyByValue for pokemon names

### ISSUE THREAD

**Issue by Jndachenhaus** [cyraxx/pogobuf#76]
This isn't so much an issue, as it is a question.

I've tried a couple different ways already, but I'm trying to modify the code in [inventory.js](https://github.com/cyraxx/pogobuf/blob/master/examples/inventory.js) to list names of the pokemon in the inventory, instead of the items.

If anyone has more experience with this, and knows how - it'd be much appreciated if you shared.

**Comment by rnd256** [comment]
Is this what you're looking for?

```
pogobuf.Utils.getEnumKeyByValue(
      POGOProtos.Enums.PokemonId,
      pokemon_id)
```

**Comment by cyraxx** [comment]
Change lines 41 to 45 in the `inventory.js` example to this:

```javascript
inventory.pokemon.forEach(pokemon => {
    console.log(pogobuf.Utils.getEnumKeyByValue(POGOProtos.Enums.PokemonId, pokemon.pokemon_id));
});
```

**Comment by Jndachenhaus** [comment]
Thanks!
