### ISSUE TITLE
fortSearch respond with experience_awarded = 0

### ISSUE THREAD

**Issue by glmn** [cyraxx/pogobuf#77]
Received `status = 1` in response of [fortSearch](https://github.com/cyraxx/pogobuf/wiki/pogobuf.Client-Pok%C3%A9mon-Go-API-Methods#fortsearchfortid-fortlatitude-fortlongitude--promise), but `experience_awarded = 0` most of the time.

**Comment by MakuraYami** [comment]
Are you getting items? And are all pokemon you try to catch fleeing? It sounds like a soft ban.

**Comment by glmn** [comment]
Usually experience_awarded equals to zero with no items dropped.
But sometimes i got 50 or 100 experience with items.

I can't understand why the most of the time i receive 0 experience.

**Comment by MakuraYami** [comment]
It is a soft ban, when you travel too fast it prevents you from spinning and all pokemon flee for about an hour. The 100 exp is when you spin 10 stops quickly after each other, obviously without being soft banned. Stop teleporting around with your coordinates and you should be good.

**Comment by glmn** [comment]
I have a 15 seconds delay between teleporting. Is it too small? Should I use another tactic instead of teleporting?

**Comment by glmn** [comment]
Increased delay value to 20 seconds, looks like it's a solution.

> Profile Updated
> Status: 1 Exp: +50
> Profile Updated
> Status: 1 Exp: +50
> Profile Updated
> Status: 1 Exp: +50
> Profile Updated
> Status: 4 Exp: +50
> Profile Updated
> Status: 4 Exp: +50
> Profile Updated
> Status: 1 Exp: +0
> Profile Updated
> Status: 1 Exp: +0
> Profile Updated
> Status: 1 Exp: +50
> Profile Updated
> Status: 1 Exp: +50
> Profile Updated
> Status: 1 Exp: +50
> Profile Updated
> Status: 1 Exp: +50

**Comment by glmn** [comment]
Maybe there is a solution to bypass soft ban wtih smaller delay value?

**Comment by MakuraYami** [comment]
You should build in set meter/second constant and make your code move there at that rate, I wouldn't go much higher then 30/mps. Either way this is a implementation issue, we try to keep issues here focused on issues or suggestions for pogobuf, so I'll close this now. Good luck.
