### ISSUE TITLE
Finer grain IV

### ISSUE THREAD

**Issue by SteinerKD** [cyraxx/pogobuf#79]
A feature request.
Would it be possible for this library to return decimal values for IV %  (just one decimal is perfectly fine)?
The standard for IV tools seems to be this one decimal precision and it makes sense as .0 and .9 (currently it's all rounded down to nearest lower full percent) isn't exactly the same thing.

**Comment by MakuraYami** [comment]
check [this line](https://github.com/cyraxx/pogobuf/blob/master/pogobuf/pogobuf.utils.js#L229)

the function is quite easy, if you want something more, make your own function and do

`var percent = Math.round((att + def + stam) / 45 * 10000) / 100;`

**Comment by SteinerKD** [comment]
Sorry, but I don't get that, because your altered function gives the exact same answer. Say 3 14 values
42/45*100=93.333333..
42/45*10000/100=93.333333..
It's still rounded down and shown as 93% (as would a result of 93.9)
I'm asking this not for my own sake, but for the program PokeNurse where I requested the same thing, and he passed me on to you and said the full % is what he get as return from your library.

**Comment by MakuraYami** [comment]
If you're gonna tell me my code doesn't work you should first test it. You improperly executed my example.

**Comment by SteinerKD** [comment]
As stated, I'm no coder and I made the request on the suggestion of another author using your code for his project (where I originally requested getting IV values with a decimal), I assume the big difference is the Math.round function, but from a mathematicians view there is no difference between the output of the two examples.
I've forwarded your code suggestion.
