### ISSUE TITLE
Undefined ghost error

### ISSUE THREAD

**Issue by maierfelix** [cyraxx/pogobuf#89]
The console logs "undefined", when google login details are wrong (possibly ptc too). I can catch the error, but it seems like some dependency fires this (maybe bluebird?).

**Comment by cyraxx** [comment]
Interesting. I've narrowed it down to the [`google.login` call](https://github.com/cyraxx/pogobuf/blob/master/pogobuf/pogobuf.googlelogin.js#L66) so it must be somewhere in the `gpsoauthnode` library.

**Comment by cyraxx** [comment]
Well, I think [this commit](https://github.com/billyriantono/gpsoauthnode/commit/dd1d805458d66be17b61ba73ae980126d47ab503) speaks for itself :smiley:

Unfortunately the fix doesn't seem to be on npm yet.

**Comment by maierfelix** [comment]
Gotcha! Thanks for pointing it out
