### ISSUE TITLE
getGymDetails

### ISSUE THREAD

**Issue by ChrisKader** [cyraxx/pogobuf#9]
Would it be possible to include gyms and stops within this request?

To detail, currently it seems to only accept actual gyms. I would like to submit any fort type or multiple (Gyms and Stops) and get back an array with maybe 2 arrays below it.

**Comment by cyraxx** [comment]
The API calls just go directly to the Pokémon Go servers, we don't have any influence on the kind of values they accept and what they return.

You could use `fortDetails()` for both forts and gyms if that gives you all the information you need. If you do need gym specific information though you'll have to make a `getGymDetails()` call for actual gyms (`fort.type == 0`).
