### ISSUE TITLE
Error with getInventory()

### ISSUE THREAD

**Issue by arvindrad** [cyraxx/pogobuf#90]
Calling client.getInventory() times out and fails, returns
Error: operation timed out after 5010 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 51

**Comment by cyraxx** [comment]
Works for me<sup>TM</sup>

Are you using the latest version? And are you supplying the `lastTimestamp` parameter? When in doubt, use 0: `client.getInventory(0)`

**Comment by Dekita** [comment]
inventory is working fine for me, im just curious about what if you constantly use 0 for the last ms timestamp? you think it would be safer to just set it to the real last ms or would using 0 over and over be ok?

**Comment by cyraxx** [comment]
It's fine to call it with 0 at the beginning of your session to get the full inventory. The app does the same.

I think for further calls you're supposed to send the time of your last call and you'll get back an inventory delta, i.e. only those items that changed since the last call.

**Comment by Dekita** [comment]
ooohhhh thats interesting! Thanks for the info :smile: 

Do you happen to know how frequent the app naturally refreshes the inventory? I assume its either a preset frequency, or whenever the user enters their inventory.

**Comment by arvindrad** [comment]
It's working fine today even though I didn't modify the code. Thanks for all the hard work you're putting into this!
