### ISSUE TITLE
Authentication delay

### ISSUE THREAD

**Issue by DVassilev** [cyraxx/pogobuf#91]
Do we need to implement a delay for PTC login? I attempted to login multiple accounts in a loop and I got the following error for all but the last 'No login ticket received from PTC login'.

Could it be related to IP bans of cloud hosting providers? I wouldn't think so due to the last account logging in but not sure.

**Comment by cyraxx** [comment]
It's quite possible that there is a limit for logins per IP address. If you are logging into multiple accounts in your code I'd advise that you implement some kind of delay logic yourself. It would be difficult to add to the login client since we don't know how exactly the rate limiting works.
