### ISSUE TITLE
Farm Pokestops?

### ISSUE THREAD

**Issue by gvsdan** [cyraxx/pogobuf#92]
is there a way to farm the pokestops nearby?

**Comment by cyraxx** [comment]
To loot pokestops, you need to call `getMapObjects()` to get the list of forts (as stops are called in the API), then call `fortDetails()` to "open" each of them and `fortSearch()` to loot. You can have a look at the [gym-details.js example](https://github.com/cyraxx/pogobuf/blob/master/examples/gym-details.js) which works with gyms, not stops, but the concept is very similar.

As for actual logic that automatically searches pokestops this isn't the right place. This is only an API library, not a botting project.

**Comment by gvsdan** [comment]
@cyraxx  thanks :D
