### ISSUE TITLE
Moving position during a Batch Call

### ISSUE THREAD

**Issue by Roguyt** [cyraxx/pogobuf#95]
Hi, 
Before beggining thank's for your awesome jobs guys !

So since two days i try to getGymDetails from my city, everything is working cool, until i wanted to go a little bit too far from the original location i set with setPosition, which return a result: 2 (Not in Range).

The problem is i can't figure it out how i can change my position during the batch which seems to doesn't work. I even tried do multiple batch call, but this doesn't work since the call are made together at the end :/

Thank's for your replies ! (Sorry for language not native)

**Comment by cyraxx** [comment]
Each batch call results in one call to the API and that call has only one set of fields for the current position. Therefore changing position within a batch call is not supported - if you change position you need to start a separate call.

**Comment by Roguyt** [comment]
Yes i know but the problem is when i do that in a forEach loop, the call batchCall() seems to be done all together which result to not change the position.

**Comment by cyraxx** [comment]
Yes, every `batchCall()` *is* one API request. It groups together all the calls made since `batchStart()` and sends them to the server as one combined request. That's the point of batch mode.

You'll need to start a new batch when you move (or not use batch mode at all). Keep in mind that you can get softbanned if you move too fast so you might have to implement a delay.

**Comment by Roguyt** [comment]
Yep but i got the same problem this is my code : 
```
			config.positions.forEach(position => {
				if (currentLocation.latitude !== position.location.latitude || currentLocation.longitude !== position.location.longitude || currentLocation.altitude !== position.location.altitude) {
					easyDebug.debug('info', 'Moving to another location.');
					client.setPosition(position.location.latitude, position.location.longitude, position.location.altitude);
					currentLocation = {
						latitude: position.location.latitude,
						longitude: position.location.longitude,
						altitude: position.location.altitude
					};
				}

				position.gyms.forEach(gym => {
					client.getGymDetails(gym.id, gym.latitude, gym.longitude)
						.then(data => {
							console.log(data.name);
						});
					console.log('Bop');
				});

				console.log('Bip');
			});

```

And that's my log :

```
clmntw@api:~/project/Pkmn-Gyms$ node app.js 
[i] Logged in.
Bop
Bop
Bop
Bop
Bip
[i] Moving to another location.
Bop
Bop
Bip
[i] Moving to another location.
Bop
Bop
Bip
Auxerre - Chapelle Du Seminaire
Monument de la gare
Caisse D'Epargne Auxerre
Cathédrale Saint Etienne D'Auxerre 
Poteaux Corniers Sculptés
Statue De Paul Bert, Auxerre

Unhandled rejection Error: operation timed out after 4671 ms, 5 tries with error: Status code 52 received from RPC
    at /home/clmntw/project/Pkmn-Gyms/node_modules/bluebird-retry/lib/bluebird-retry.js:102:35
    at tryCatcher (/home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/util.js:16:23)
    at /home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/catch_filter.js:24:41
    at tryCatcher (/home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/promise.js:681:18)
    at Async._drainQueue (/home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/clmntw/project/Pkmn-Gyms/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by MakuraYami** [comment]
I think your logic is flawed. Doing a call on the pogobuf client (batch or not) is a asynchronous method. This means it's going to do the call but meanwhile the rest of the code continues, this causes everything to be send at once surely giving you status 52 errors for spam. You should write proper asynchronous code with delays between each call, once you do that I think this problem will solve itself.

**Comment by Roguyt** [comment]
Using @cyraxx and @MakuraYami advices i fixed my code thank's guys !
