### ISSUE TITLE
#question empty arrays

### ISSUE THREAD

**Issue by dabnoj** [cyraxx/pogobuf#96]
when i try to get map object (since 10 minutes) it returns me empty arrays like that

```
Array[0]
current_timestamp_ms
:
1472072601297
decimated_spawn_points
:
Array[0]
deleted_objects
:
Array[0]
fort_summaries
:
Array[0]
forts
:
Array[0]
is_truncated_list
:
false
nearby_pokemons
:
Array[0]
s2_cell_id
:
"9926595584582483968"
spawn_points
:
Array[0]
wild_pokemons
:
Array[0]
__proto__
:
ProtoBuf.Builder.Builder.Message
```

do you know why?

**Comment by cyraxx** [comment]
It's working fine for me currently.

Apparently there was an issue with the servers just recently that caused them to always return empty responses, including in the actual app.

**Comment by dabnoj** [comment]
yes ty it works fine now, im afraid cause theyll update api soon, will you keep it up to date?

**Comment by cyraxx** [comment]
Generally yes, we try to keep pogobuf up to date with any API changes as quickly as possible.
