### ISSUE TITLE
getMapObjects response delay

### ISSUE THREAD

**Issue by jmbrito01** [cyraxx/pogobuf#98]
Hi, i was using the api and created something like a bot to walk, catch pokemons and loot pokestops. What i noticed is that the getMapObjects is increasing a lot the time needed to complete the task( Adds around 9 seconds to the function ). I was wondering, is this a forced wait or it's something i'm doing wrong?

**Comment by cyraxx** [comment]
This is intentional, there is a minimum delay between `getMapObjects` calls per API session. The exact number of seconds is taken from the client settings that are received from the server during `init()`.

**Comment by SkelletonX** [comment]
Lovely
